"""
일일 리포트 생성기
- 거래 요약
- Health 상태
- Markdown 출력
- 원자적 저장 (tmp → replace)
"""

import logging
import os
from datetime import date, datetime
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


class DailyReportGenerator:
    """
    일일 리포트 생성기

    출력: logs/reports/daily_YYYY-MM-DD.md
    """

    DEFAULT_REPORT_DIR = "logs/reports"

    def __init__(
        self, trade_logger=None, health_monitor=None, report_dir: Optional[str] = None
    ):
        """초기화"""
        self.trade_logger = trade_logger
        self.health_monitor = health_monitor
        self.report_dir = Path(report_dir or self.DEFAULT_REPORT_DIR)
        self.report_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _to_float(v: Any, default: float = 0.0) -> float:
        """안전한 float 변환"""
        if v is None:
            return default
        if isinstance(v, (int, float)):
            return float(v)
        s = str(v).strip()
        if s == "":
            return default
        try:
            return float(s)
        except (ValueError, TypeError):
            return default

    def generate(self, report_date: Optional[date] = None) -> str:
        """일일 리포트 생성"""
        d = report_date or date.today()

        trade_summary: Dict = {}
        if self.trade_logger:
            trade_summary = self.trade_logger.get_daily_summary(d)

        health_summary: Dict = {}
        if self.health_monitor:
            if hasattr(self.health_monitor, "get_summary"):
                health_summary = self.health_monitor.get_summary()

        report = self._build_report(d, trade_summary, health_summary)

        # 원자적 저장: tmp → replace
        file_path = self.report_dir / f"daily_{d.strftime('%Y-%m-%d')}.md"
        tmp_path = file_path.with_suffix(".md.tmp")

        try:
            with open(tmp_path, "w", encoding="utf-8") as f:
                f.write(report)
            os.replace(tmp_path, file_path)
            logger.info(f"[DailyReport] Generated: {file_path}")
        except Exception as e:
            logger.error(f"[DailyReport] Save failed: {e}")
            if tmp_path.exists():
                tmp_path.unlink()

        return report

    def _build_report(self, d: date, trades: Dict, health: Dict) -> str:
        """Markdown 리포트 빌드"""

        status = health.get("status", "N/A")
        status_emoji = {
            "HEALTHY": "✅",
            "WARNING": "⚠️",
            "CRITICAL": "🔴",
            "HALTED": "⛔",
        }.get(status, "❓")

        mdd = self._to_float(health.get("mdd_pct", 0))
        mdd_status = (
            "🔴 CRITICAL" if mdd > 15 else ("⚠️ WARNING" if mdd > 10 else "✅ OK")
        )

        triggers = health.get("triggers", [])
        triggers_str = "\n".join(f"- {t}" for t in triggers) if triggers else "- None"

        # 숫자 안전 변환
        total_trades = int(self._to_float(trades.get("total_trades", 0)))
        buy_count = int(self._to_float(trades.get("buy_count", 0)))
        sell_count = int(self._to_float(trades.get("sell_count", 0)))
        total_volume = self._to_float(trades.get("total_volume", 0))
        total_fee = self._to_float(trades.get("total_fee", 0))
        total_pnl = self._to_float(trades.get("total_pnl", 0))

        report = f"""# Daily Trading Report

**Date**: {d.strftime('%Y-%m-%d')}
**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## 📊 Trading Summary

| Metric | Value |
|--------|-------|
| Total Trades | {total_trades} |
| Buy Orders | {buy_count} |
| Sell Orders | {sell_count} |
| Total Volume | {total_volume:,.0f} KRW |
| Total Fees | {total_fee:,.0f} KRW |
| Daily PnL | {total_pnl:+,.0f} KRW |

---

## 🏥 Strategy Health

| Metric | Value | Status |
|--------|-------|--------|
| Status | {status} | {status_emoji} |
| Sharpe (30d) | {health.get('sharpe_30d', 'N/A')} | - |
| MDD | {mdd:.2f}% | {mdd_status} |
| Consecutive Losses | {health.get('consecutive_losses', 0)} | - |

### Triggers
{triggers_str}

### Recommendation
> {health.get('recommendation', 'No data available')}

---

## 📝 Notes

- (Manual notes here)

---

*Generated by MASP v1.0*
"""
        return report

    def print_summary(self, report_date: Optional[date] = None) -> None:
        """콘솔 요약 출력"""
        d = report_date or date.today()

        summary: Dict = {}
        if self.trade_logger:
            summary = self.trade_logger.get_daily_summary(d)

        total_trades = int(self._to_float(summary.get("total_trades", 0)))
        buy_count = int(self._to_float(summary.get("buy_count", 0)))
        sell_count = int(self._to_float(summary.get("sell_count", 0)))
        total_volume = self._to_float(summary.get("total_volume", 0))
        total_fee = self._to_float(summary.get("total_fee", 0))
        total_pnl = self._to_float(summary.get("total_pnl", 0))

        print(f"\n{'='*50}")
        print(f"Daily Summary: {d}")
        print(f"{'='*50}")
        print(f"Trades: {total_trades} (B:{buy_count} / S:{sell_count})")
        print(f"Volume: {total_volume:,.0f} KRW")
        print(f"Fees: {total_fee:,.0f} KRW")
        print(f"PnL: {total_pnl:+,.0f} KRW")
        print(f"{'='*50}\n")
